region: 'us-west'
user: 'koalakakapo'
api-key: '23718af6-687d-447e-ac91-92f526829723'
# this is my log file for SC I use for Mac OS tests.
logfile: '/sc-test.log'
# this is the tunnel I use for Mac OS tests
tunnel-identifier: 'kp001'