name: Selenium with TestNG - CI
 
on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
 
jobs:
 lint:
   name: Linter
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         fetch-depth: 0

     - name: Linter     
       uses: github/super-linter@v4
       env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: test

 hello_world_job:
   runs-on: ubuntu-latest
   name: A job to say hello
   outputs:
     random_number: ${{ steps.foo.outputs.random.number }}
   steps:
     - uses: actions/checkout@v3
     - id: foo
       uses: ./github/actions/actions/1st
       with:
        who-to-greet: 'Koala and Kakapo!'
     - run: echo random-number ${{ steps.foo.outputs.random.number }}
       shell: bash

 hello_world_job2:
   runs-on: ubuntu-latest
   name: A job to say hello
   outputs:
     random_number: ${{ steps.foo.outputs.random.number }}
   steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./github/actions/actions/2nd
        with:
         who-to-greet: 'Hippo and Turtle!'
      - run: echo random-number ${{ steps.foo.outputs.random.number }}
        shell: bash

 build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'microsoft'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean test -Dbaseurl="https://saucelabs.com/" -DsuiteXmlFile="testng.xml"
