name: Selenium with TestNG - CI
 
on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        fetch-depth: 0
        java-version: '11'
        distribution: 'microsoft'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean test -DsuiteXmlFile="testng.xml"
