name: Selenium with TestNG - CI
 
on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
 
jobs:
 lint:
   name: Linter
   runs-on: ubntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
         fetch-depth: 0

     - name: Linter     
       uses: github/super-linter@v4
       env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: test

 build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'microsoft'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean test -DsuiteXmlFile="testng.xml"
