name: SauceLabs with TestNG - CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

  jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:
      -uses: actions/checkout@v3
      -name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'microsoft'
         cache: maven

     # ...
     - uses: saucelabs/sauce-connect-action@v2
       with:
         username: ${{secrets.SAUCE_USERNAME}}
         accessKey: ${{secrets.SAUCE_ACCESS_KEY}}
         tunnelName: gg101
         configFile: ${{github.workspace}}/sc-configuration/config.yaml
      # ...

     - name: Build with Maven
       run: mvn -B clean test -Dbaseurl="https://saucelabs.com/" -DsuiteXmlFile="testng.xml"

